#!/bin/bash

make clean

find -iname 'CMakeCache.txt'  -exec rm -rf {} \+
find -iname 'cmake_install.cmake'  -exec rm -rf {} \+
find -iname 'Makefile'  -exec rm -rf {} \+
find -iname 'CMakeFiles'  -exec rm -rf {} \+
find -iname '*.size'  -exec rm -rf {} \+
find -iname '*.bin'  -exec rm -rf {} \+
find -iname '*.eep'  -exec rm -rf {} \+
find -iname '*.cproject'  -exec rm -rf {} \+
find -iname '*.project'  -exec rm -rf {} \+
find -iname '*.hex' -not -name '*-cheali-charger*.hex' -exec rm -rf {} \+
#find -iname '*.hex'  -exec rm -rf {} \+
find -iname '*.bak'  -exec rm -rf {} \+

find src/hardware/*/*.hex -delete


