# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/njozsef/cheali-git/cheali-charger-test1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/njozsef/cheali-git/cheali-charger-test1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/njozsef/cheali-git/cheali-charger-test1/CMakeFiles /home/njozsef/cheali-git/cheali-charger-test1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/njozsef/cheali-git/cheali-charger-test1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arduino

# Build rule for target.
arduino: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arduino
.PHONY : arduino

# fast build rule for target.
arduino/fast:
	$(MAKE) -f arduino/cores/arduino/CMakeFiles/arduino.dir/build.make arduino/cores/arduino/CMakeFiles/arduino.dir/build
.PHONY : arduino/fast

#=============================================================================
# Target rules for targets named cheali-charger-GTPowerA6-10-0.31

# Build rule for target.
cheali-charger-GTPowerA6-10-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-GTPowerA6-10-0.31
.PHONY : cheali-charger-GTPowerA6-10-0.31

# fast build rule for target.
cheali-charger-GTPowerA6-10-0.31/fast:
	$(MAKE) -f src/hardware/GTPowerA6-10-original/CMakeFiles/cheali-charger-GTPowerA6-10-0.31.dir/build.make src/hardware/GTPowerA6-10-original/CMakeFiles/cheali-charger-GTPowerA6-10-0.31.dir/build
.PHONY : cheali-charger-GTPowerA6-10-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-GTPowerA6-10-0.31.size

# Build rule for target.
cheali-charger-GTPowerA6-10-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-GTPowerA6-10-0.31.size
.PHONY : cheali-charger-GTPowerA6-10-0.31.size

# fast build rule for target.
cheali-charger-GTPowerA6-10-0.31.size/fast:
	$(MAKE) -f src/hardware/GTPowerA6-10-original/CMakeFiles/cheali-charger-GTPowerA6-10-0.31.size.dir/build.make src/hardware/GTPowerA6-10-original/CMakeFiles/cheali-charger-GTPowerA6-10-0.31.size.dir/build
.PHONY : cheali-charger-GTPowerA6-10-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-imaxB6-original-0.31

# Build rule for target.
cheali-charger-imaxB6-original-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-imaxB6-original-0.31
.PHONY : cheali-charger-imaxB6-original-0.31

# fast build rule for target.
cheali-charger-imaxB6-original-0.31/fast:
	$(MAKE) -f src/hardware/imaxB6-original/CMakeFiles/cheali-charger-imaxB6-original-0.31.dir/build.make src/hardware/imaxB6-original/CMakeFiles/cheali-charger-imaxB6-original-0.31.dir/build
.PHONY : cheali-charger-imaxB6-original-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-imaxB6-original-0.31.size

# Build rule for target.
cheali-charger-imaxB6-original-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-imaxB6-original-0.31.size
.PHONY : cheali-charger-imaxB6-original-0.31.size

# fast build rule for target.
cheali-charger-imaxB6-original-0.31.size/fast:
	$(MAKE) -f src/hardware/imaxB6-original/CMakeFiles/cheali-charger-imaxB6-original-0.31.size.dir/build.make src/hardware/imaxB6-original/CMakeFiles/cheali-charger-imaxB6-original-0.31.size.dir/build
.PHONY : cheali-charger-imaxB6-original-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-imaxB6-clone-0.31

# Build rule for target.
cheali-charger-imaxB6-clone-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-imaxB6-clone-0.31
.PHONY : cheali-charger-imaxB6-clone-0.31

# fast build rule for target.
cheali-charger-imaxB6-clone-0.31/fast:
	$(MAKE) -f src/hardware/imaxB6-clone/CMakeFiles/cheali-charger-imaxB6-clone-0.31.dir/build.make src/hardware/imaxB6-clone/CMakeFiles/cheali-charger-imaxB6-clone-0.31.dir/build
.PHONY : cheali-charger-imaxB6-clone-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-imaxB6-clone-0.31.size

# Build rule for target.
cheali-charger-imaxB6-clone-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-imaxB6-clone-0.31.size
.PHONY : cheali-charger-imaxB6-clone-0.31.size

# fast build rule for target.
cheali-charger-imaxB6-clone-0.31.size/fast:
	$(MAKE) -f src/hardware/imaxB6-clone/CMakeFiles/cheali-charger-imaxB6-clone-0.31.size.dir/build.make src/hardware/imaxB6-clone/CMakeFiles/cheali-charger-imaxB6-clone-0.31.size.dir/build
.PHONY : cheali-charger-imaxB6-clone-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-Accucel-6-50W-5A-0.31

# Build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-5A-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-Accucel-6-50W-5A-0.31
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-5A-0.31

# fast build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-5A-0.31/fast:
	$(MAKE) -f src/hardware/Turnigy-Accucel-6-50W-5A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.dir/build.make src/hardware/Turnigy-Accucel-6-50W-5A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.dir/build
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-5A-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size

# Build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size

# fast build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size/fast:
	$(MAKE) -f src/hardware/Turnigy-Accucel-6-50W-5A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size.dir/build.make src/hardware/Turnigy-Accucel-6-50W-5A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size.dir/build
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-Accucel-6-50W-6A-0.31

# Build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-6A-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-Accucel-6-50W-6A-0.31
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-6A-0.31

# fast build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-6A-0.31/fast:
	$(MAKE) -f src/hardware/Turnigy-Accucel-6-50W-6A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.dir/build.make src/hardware/Turnigy-Accucel-6-50W-6A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.dir/build
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-6A-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size

# Build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size

# fast build rule for target.
cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size/fast:
	$(MAKE) -f src/hardware/Turnigy-Accucel-6-50W-6A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size.dir/build.make src/hardware/Turnigy-Accucel-6-50W-6A/CMakeFiles/cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size.dir/build
.PHONY : cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-MEGA-400Wx2-0.31

# Build rule for target.
cheali-charger-Turnigy-MEGA-400Wx2-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-MEGA-400Wx2-0.31
.PHONY : cheali-charger-Turnigy-MEGA-400Wx2-0.31

# fast build rule for target.
cheali-charger-Turnigy-MEGA-400Wx2-0.31/fast:
	$(MAKE) -f src/hardware/Turnigy-MEGA-400Wx2/CMakeFiles/cheali-charger-Turnigy-MEGA-400Wx2-0.31.dir/build.make src/hardware/Turnigy-MEGA-400Wx2/CMakeFiles/cheali-charger-Turnigy-MEGA-400Wx2-0.31.dir/build
.PHONY : cheali-charger-Turnigy-MEGA-400Wx2-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-MEGA-400Wx2-0.31.size

# Build rule for target.
cheali-charger-Turnigy-MEGA-400Wx2-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-MEGA-400Wx2-0.31.size
.PHONY : cheali-charger-Turnigy-MEGA-400Wx2-0.31.size

# fast build rule for target.
cheali-charger-Turnigy-MEGA-400Wx2-0.31.size/fast:
	$(MAKE) -f src/hardware/Turnigy-MEGA-400Wx2/CMakeFiles/cheali-charger-Turnigy-MEGA-400Wx2-0.31.size.dir/build.make src/hardware/Turnigy-MEGA-400Wx2/CMakeFiles/cheali-charger-Turnigy-MEGA-400Wx2-0.31.size.dir/build
.PHONY : cheali-charger-Turnigy-MEGA-400Wx2-0.31.size/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-A-6-10-200W-0.31

# Build rule for target.
cheali-charger-Turnigy-A-6-10-200W-0.31: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-A-6-10-200W-0.31
.PHONY : cheali-charger-Turnigy-A-6-10-200W-0.31

# fast build rule for target.
cheali-charger-Turnigy-A-6-10-200W-0.31/fast:
	$(MAKE) -f src/hardware/Turnigy-A-6-10-200W/CMakeFiles/cheali-charger-Turnigy-A-6-10-200W-0.31.dir/build.make src/hardware/Turnigy-A-6-10-200W/CMakeFiles/cheali-charger-Turnigy-A-6-10-200W-0.31.dir/build
.PHONY : cheali-charger-Turnigy-A-6-10-200W-0.31/fast

#=============================================================================
# Target rules for targets named cheali-charger-Turnigy-A-6-10-200W-0.31.size

# Build rule for target.
cheali-charger-Turnigy-A-6-10-200W-0.31.size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheali-charger-Turnigy-A-6-10-200W-0.31.size
.PHONY : cheali-charger-Turnigy-A-6-10-200W-0.31.size

# fast build rule for target.
cheali-charger-Turnigy-A-6-10-200W-0.31.size/fast:
	$(MAKE) -f src/hardware/Turnigy-A-6-10-200W/CMakeFiles/cheali-charger-Turnigy-A-6-10-200W-0.31.size.dir/build.make src/hardware/Turnigy-A-6-10-200W/CMakeFiles/cheali-charger-Turnigy-A-6-10-200W-0.31.size.dir/build
.PHONY : cheali-charger-Turnigy-A-6-10-200W-0.31.size/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arduino"
	@echo "... cheali-charger-GTPowerA6-10-0.31"
	@echo "... cheali-charger-GTPowerA6-10-0.31.size"
	@echo "... cheali-charger-imaxB6-original-0.31"
	@echo "... cheali-charger-imaxB6-original-0.31.size"
	@echo "... cheali-charger-imaxB6-clone-0.31"
	@echo "... cheali-charger-imaxB6-clone-0.31.size"
	@echo "... cheali-charger-Turnigy-Accucel-6-50W-5A-0.31"
	@echo "... cheali-charger-Turnigy-Accucel-6-50W-5A-0.31.size"
	@echo "... cheali-charger-Turnigy-Accucel-6-50W-6A-0.31"
	@echo "... cheali-charger-Turnigy-Accucel-6-50W-6A-0.31.size"
	@echo "... cheali-charger-Turnigy-MEGA-400Wx2-0.31"
	@echo "... cheali-charger-Turnigy-MEGA-400Wx2-0.31.size"
	@echo "... cheali-charger-Turnigy-A-6-10-200W-0.31"
	@echo "... cheali-charger-Turnigy-A-6-10-200W-0.31.size"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

