#!/bin/bash

TTY=$1
#TTY=/dev/ttyUSB0
SPEED=9600

stty -F $TTY cs8 $SPEED ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts -clocal