#ifndef VERSION_H_
#define VERSION_H_

#define CHEALI_CHARGER_VERSION_MAJOR 0
#define CHEALI_CHARGER_VERSION_MINOR 10

#define CHEALI_CHARGER_EEPROM_VERSION 2


#define CHEALI_CHARGER_STRING2(x) #x
#define CHEALI_CHARGER_STRING(x) CHEALI_CHARGER_STRING2(x)

#define CHEALI_CHARGER_VERSION_STRING  CHEALI_CHARGER_STRING(CHEALI_CHARGER_VERSION_MAJOR)  \
			"." CHEALI_CHARGER_STRING(CHEALI_CHARGER_VERSION_MINOR)

#define CHEALI_CHARGER_EPPROM_VERSION_STRING  CHEALI_CHARGER_STRING(CHEALI_CHARGER_EEPROM_VERSION)


class Version {
public:
	static int getCurrentEEPROMVersion();
	static void restoreDefault();
};


#endif /* VERSION_H_ */
