name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake avr-libc gcc-avr git
          version: 1.0
      - uses: actions/checkout@v3
#       - name: Install Dependencies
#         run: | 
#             sudo apt-get install cmake avr-libc gcc-avr git
      - name: Prepare Env
        run: | 
            git submodule init
            git submodule update
            ./bootstrap-avr
            make
            
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v3
        with:
          path: | 
                src/hardware/atmega32/targets/**
