name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake avr-libc gcc-avr git
          version: 1.0
      - uses: actions/checkout@v3

      - name: Build Project
        run: | 
            git submodule init
            git submodule update
            ./bootstrap-avr
            make
            
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: atmega32
          path: | 
                src/hardware/atmega32/targets/**/*.hex
                src/hardware/atmega32/targets/**/progUSBasp.sh
