name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Prepare Env
        run: | 
            sudo apt-get install cmake avrdude avr-libc gcc-avr git
            git clone https://github.com/stawel/cheali-charger.git
            cd cheali-charger
            git submodule init
            git submodule update
            ./bootstrap-avr
            make       
            
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v3
        with:
          path: | 
                src/hardware/atmega32/targets/**/progUSBasp.sh
                src/hardware/atmega32/targets/**/**.hex
