 # This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the action will run. 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Prepare Env
        run: | 
            sudo apt-get install cmake avrdude avr-libc gcc-avr git
            git clone https://github.com/stawel/cheali-charger.git
            cd cheali-charger
            git submodule init
            git submodule update
            ./bootstrap-avr
            make
      
#       - name: Build Submodules
#         run: |    
#             ./scripts/compile_ci_pre.sh

#       - name: Build stuff
#         run: |    
#             ./scripts/compile_ci_post.sh

#       - name: Pack stuff
#         run: |    
#             sudo ./scripts/pack_fw.all.sh
#             ls -la
#             pwd           
            
#       - name: Upload Artifact GK-200MP2B
#         uses: actions/upload-artifact@v2
#         with:
#           name: GK-200MP2B.tar.gz
#           path: out/GK-200MP2B/**.tgz

#       - name: Upload Artifact GK-200MP2C
#         uses: actions/upload-artifact@v2
#         with:
#           name: GK-200MP2C.tar.gz
#           path: out/GK-200MP2C/**.tgz%    
